version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./server/data/postgresql/:/var/lib/postgresql/data

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8001:8001"
